@startuml Platform_changes
!pragma layout smetana
title Platform Changes
package platforms {
    package platforms/abstract.py {
        abstract class AbstractPlatform_New {
            name
            runcard
            settings
            is_connected
            --
            __init__(name, runcard)
            __call__(sequence, nshots=None)
            _check_connected()
            reload_settings()
            ..
            {abstract} run_calibration(runcard)
            {abstract} connect()
            {abstract} setup()
            {abstract} start()
            {abstract} stop()
            {abstract} disconnect()
            {abstract} execute_pulse_sequence(sequence, nshots=None)
        }
        abstract class AbstractPlatform_Old {
            name
            runcard
            _settings
            is_connected
            --
            settingsdata_folder
            hardware_avg
            sampling_rate
            software_averages
            repetition_duration
            resonator_frequency
            qubit_frequency
            pi_pulse_gain
            pi_pulse_amplitude
            pi_pulse_duration
            pi_pulse_frequency
            readout_pulse
            max_readout_voltage
            min_readout_voltage
            delay_between_pulses
            delay_before_readout
            --
            __init__(name, runcard)
            __getstate__()
            __setstate__(data)
            __call__(sequence, nshots=None)
            _check_connected()
            reload_settings()
            ..
            {abstract} run_calibration(show_plots=False)
            {abstract} connect()
            {abstract} setup()
            {abstract} start()
            {abstract} stop()
            {abstract} disconnect()
            {abstract} execute(sequence, nshots=None)
        }
    }
}


'hide members

@enduml