[project]
name = "qibolab"
version = "0.2.17"
description = "Quantum hardware module and drivers for Qibo"
authors = [{name = "The Qibo team"}]
license = "Apache-2.0"
license-files = ["LICENSE"]
readme = "README.md"
keywords = []
classifiers = [
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Scientific/Engineering :: Physics",
]
requires-python = ">=3.11,<3.14"
dependencies = [
  "numpy>=2.0.0,<3.0.0",
  "scipy>=1.13.0,<2.0.0",
  "pydantic>=2.4.0,<3.0.0",
]

[project.urls]
Homepage = "https://qibo.science/"
Repository = "https://github.com/qiboteam/qibolab/"
Documentation = "https://qibo.science/docs/qibolab/stable"

[project.optional-dependencies]
backend = ["qibo"]
emulator = ["qutip", "dynamiqs"]
qrng = ["pyserial"]

[dependency-groups]
dev = [
  "pudb>=2025.1,<2026.0",
  "ipython>=8.12.0,<9.0.0",
]
docs = [
  "sphinx>=8.2,<9.0",
  "furo>=2025.7.19,<2026.0.0",
  "recommonmark>=0.7.1,<0.8.0",
  "sphinxcontrib-bibtex>=2.5.0,<3.0.0",
  "sphinx-markdown-tables>=0.0.17,<0.0.18",
  "nbsphinx>=0.9.1,<0.10.0",
  "ipython>=8.12.0,<9.0.0",
  "sphinx-copybutton>=0.5.1,<0.6.0",
  # extras
  "qcodes>=0.52.0,<0.53.0",
  "qcodes_contrib_drivers>=0.23.0,<0.24.0",
  "qutip>=5.0.2,<6.0.0",
]
tests = [
  "pytest>=7.2.2",
  "pytest-cov>=4.0.0,<5.0.0",
  "pytest-env>=0.8.1",
  "pytest-mock>=3.10.0",
  "qcodes>=0.52.0,<0.53.0",
  "qcodes_contrib_drivers>=0.23.0,<0.24.0",
  "requests>=2.32.0,<3.0.0",
]
analysis = [
  "ruff>=0.16.0,<0.17.0",
]

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[tool.poe.tasks]
test = "pytest"
lint = "ruff check"
lint-warnings = """
  ruff check --exit-zero \
  --select F,E,W,C90,N,UP,BLE,FBT,B,A,C4,T10,EM,EXE,ISC,ICN,LOG,G,INP,PIE,T20,PT,Q,RSE,\
           RET,SLF,SLOT,SIM,TC,INT,ARG,PTH,ERA,NPY,PERF,RUF
""" # these are some extra strict checks, but just for reporting purposes
types = "true"
docs = "make -C doc html"
docs-clean = "make -C doc clean"
test-docs = "make -C doc doctest"

[tool.pytest.ini_options]
testpaths = ['tests/']
addopts = [
  '--cov=qibolab',
  '--cov-report=xml',
  '--cov-report=html',
  "--ignore=tests/qblox", # TODO: move tests to qibolab-qblox
]

[tool.ruff]
target-version = "py311"
line-length = 88

[tool.ruff.lint]
extend-select = ["I","UP", "D103","D200","D206","D300","D301"] # I -> pycln, D->pydocstyle, UP->pyupgrade

[tool.ruff.lint.per-file-ignores]
"!src/**/*" = ["D103", "D200", "D206", "D300", "D301"] # skip for non src/ files
"src/qibolab/_core/instruments/qm/program/loops.py" = ["TRY002"] # Create your own exception
