from qibo import Circuit, __version__

from qibolab import execute_qasm
from qibolab.backends import QibolabBackend


def test_execute_qasm():
    qasm_string = f"""// Generated by QIBO {__version__}
OPENQASM 2.0;
include "qelib1.inc";
qreg q[3];
creg a[2];
cx q[0],q[2];
x q[1];
swap q[0],q[1];
cx q[1],q[0];
measure q[0] -> a[0];
measure q[2] -> a[1];"""
    c = Circuit.from_qasm(qasm_string)
    backend = QibolabBackend("dummy")
    qasm_res = execute_qasm(qasm_string, platform="dummy")
    res = backend.execute_circuit(c)
    backend.assert_allclose(qasm_res.probabilities(), res.probabilities(), atol=1e-1)
