name: tiiq_single_qubit_diagnostics
description: Settings for diagnostic sweeps.

resonator_spectroscopy:
  lowres_width: 30.0e+6
  lowres_step: 2.0e+6
  highres_width: 1.0e+6
  highres_step: 0.2e+6
  precision_width: 0.5e+6
  precision_step: 0.02e+6

qubit_spectroscopy:
  fast_start: -400.0e+6
  fast_end: 100.0e+6
  fast_step: 2.0e+6
  precision_start: -30.0e+6
  precision_end: 30.0e+6
  precision_step: 0.5e+6

t1:
  delay_before_readout_start: 0
  delay_before_readout_end: 4500
  delay_before_readout_step: 30

ramsey:
  start_start: 4
  start_end: 1000
  start_step: 4

spin_echo:
  start_start: 4
  start_end: 500
  start_step: 10
