name: Deploy docs


on:
  workflow_dispatch:
  push:
      branches: [master,deploy_workflow] # TODO: remove "deploy_workflow"

jobs:

  deploy-docs:
    uses: qibogang/workflows/.github/workflows/deploy-sphinx-docs-to-ghpages.yml@cache_pip
    with:
      python-version: 3.9
